# Objective:
Can you differentiate a weed from a crop seedling? Given an image
differentiate between different plant types.

Tthis dataset gives you an opportunity to experiment with different image
recognition techniques, as well to provide a place to cross-pollenate ideas.

# Context:
The ability to do so effectively can mean better crop yields and better stewardship of the environment.

The Aarhus University Signal Processing group, in collaboration with University of Southern Denmark, has recently released a dataset containing images of approximately 960 unique plants belonging to 12 species at several growth stages.

# Data Description:
You are provided with a training set and a test set of images of plant seedlings at various stages of grown. Each image has a filename that is its unique id. The dataset comprises 12 plant species. The goal of the competition is to create a classifier capable of determining a plant's species from a photo. The list of species is as follows:
- Black-grass
- Charlock
- Cleavers
- Common Chickweed
- Common wheat
- Fat Hen
- Loose Silky-bent
- Maize
- Scentless Mayweed
- Shepherds Purse
- Small-flowered Cranesbill
- Sugar beet

Know more at :
https://www.kaggle.com/c/plant-seedlings-classification/data

# Steps and Milestones (100%):
- Setup Environment and Load Necessary Packages (5%)
- Data Preparation (40%)
    - Loading Data (5%)
    - Cleaning Data (10%)
    - Data Representation & Feature Engineering (If Any) (15%)
    - Creating Train and Validation Set (10%)

- Model Creation (30%)
    - Write & Configure Model (10%)
    - Compile Model (10%)
    - Build Model & Checking Summary (10%)

- Training and Evaluation (25%)
    - Run Multiple Experiments (10%)
    - Reason & Visualize Model Performance (5%)
    - Evaluate Model on Test Set (10%)

# Learning Outcomes:
- Image classification
- Neural Networks
- Convolutional Neural Networks
- Dynamic Input Image Pipeline
- Fine-tuning Model
- Data Preparation
- Visualization

# STEPS
1. Read the images and generate the train and test dataset (5 points)
2. Divide the data set into Train and validation data sets
3. Initialize & build the model (10 points)
4. Optimize the model (8 points)
5. Predict the accuracy for both train and validation data (7 points)

# STEP 1
Read the images and generate the train and test dataset (5 points)

In [1]:

# Loop through folders
    # In each folder, read each image
        # Resize the images to common size (say 128 * 128)
        # Save the images pixel values, after resizing, along with the classification value in a list of array of arrays
        # Save the data to a file (probably to .h5)
# Work on the saved file


In [1]:
import skimage.io as io

# For viewing the image
import matplotlib.pyplot as plt
%matplotlib inline

#Importing opencv module for the resizing function
import cv2

import glob, os

import numpy as np
import h5py
from sklearn.model_selection import train_test_split

In [3]:
rootdir_trainingData = 'D:/workingDirectory/PROJECTS/11 - PROJECT - R7 - 01 - Computer Vision with CNN/plant-seedlings-classification/train'

rootdir_testingData = 'D:/workingDirectory/PROJECTS/11 - PROJECT - R7 - 01 - Computer Vision with CNN/plant-seedlings-classification/test'

In [4]:
# for subdir, dirs, files in os.walk(rootdir):
#     for directory in dirs:
#         print(directory)

# for subdir, dirs, files in os.walk(rootdir):
#     for file in files:
#         print(os.path.join(subdir, file))

# for subdir, dirs, files in os.walk(rootdir):
#     for directory in dirs:
#         print(directory)
#         for file in files:
#             img = io.imread('IMG_20190821_113948.jpg')

# img = io.imread(os.path.join(rootdir + "/" + "Black-grass", "0ace21089.png"))
# plt.figure(figsize=[10,10])
# plt.imshow(img)

# plt.figure(figsize=[10,10])
# plt.imshow(img_res.astype('uint8'))
# plt.show()

In [5]:
def resizeToDesiredShape(inputImage, h, w):
    # Seperate the r, g, b layers
    r_array = np.array(inputImage[:, :, 0])
    g_array = np.array(inputImage[:, :, 1])
    b_array = np.array(inputImage[:, :, 2])
    
    # Apply resize on each layer (r, g, b)
    r_res = cv2.resize(r_array, dsize=(h, w), interpolation=cv2.INTER_CUBIC)
    g_res = cv2.resize(r_array, dsize=(h, w), interpolation=cv2.INTER_CUBIC)
    b_res = cv2.resize(r_array, dsize=(h, w), interpolation=cv2.INTER_CUBIC)
    
    # Prepare image using the resized r, g, b
    outputImage = np.array([r_res, g_res, b_res])  # Put the reshaped values into a array
    outputImage = np.transpose(outputImage, (1, 2, 0))  # Swap the dimensions of the array

    return outputImage

In [6]:
# Function to read the images, reshize them and add to an list
def generateX_y(rootDir, h=512, w=512, y_inOut = True):
    X_out = []
    y_out = []
    
    # Get all possible seed types (=folder names)
    if y_inOut:
        possibleY = []
        for subdir, dirs, files in os.walk(rootdir_trainingData):
            possibleY = dirs
            break
    
    for subdir, dirs, files in os.walk(rootDir):
        for file in files:
            
            # Append y
            if y_inOut:
                presentDirLabel = subdir.split("\\")[-1]
                presentDirIndex = possibleY.index(presentDirLabel)
                y_out.append(presentDirIndex)
            # Resize and append X
            img = io.imread(os.path.join(subdir, file))
            img_res = resizeToDesiredShape(img, h, w)
            
            X_out.append(img_res)
    return X_out, y_out

In [2]:
res_dim_h = 128  # Resize height
res_dim_w = 128  # Resize width

In [ ]:
X_train, y_train = generateX_y(rootdir_trainingData, res_dim_h, res_dim_w)
X_test, y_test = generateX_y(rootdir_testingData, res_dim_h, res_dim_w, y_inOut=False)

print(len(X_train))  # Should return 4750
print(len(X_test))  # Should return 794

In [8]:
# Save data to HDF5 file (commented to avoid running again)

# hf = h5py.File('data_plant_seed_resizedImages.h5', 'w')  # Create file with write(w) access
# hf.create_dataset('X_train_val', data=X_train)
# hf.create_dataset('y_train_val', data=y_train)
# hf.create_dataset('X_test', data=X_test)
# hf.close()

In [9]:
h5 = h5py.File('data_plant_seed_resizedImages.h5', 'r')
h5.keys()

<KeysViewHDF5 ['X_test', 'X_train_val', 'y_train_val']>

In [10]:
h5f = h5py.File('data_plant_seed_resizedImages.h5', 'r')
X_train_val = h5f['X_train_val'][:]
y_train_val = h5f['y_train_val'][:]
X_test = h5f['X_test'][:]

# STEP 2
Divide the data set into Train and validation data sets

In [11]:
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.3)

In [12]:
print(len(X_train))
print(len(X_val))
print(len(y_train))
print(len(y_val))

3325
1425
3325
1425


# STEP 3
Initialize & build the model (10 points)

In [13]:
# Convert list to array
X_train = np.asarray(X_train)
X_val = np.asarray(X_val)
X_test = np.asarray(X_test)

In [14]:
X_train = X_train.astype('float32')
X_val = X_val.astype('float32')
X_test = X_test.astype('float32')

In [15]:
# Normalizing the data
X_train /= 255
X_val /= 255
X_test /= 255

In [18]:
# Save normalized value to .h5 file (commented to avoid running again)

# hf = h5py.File('data_plant_seed_resizedImages_float_normalized.h5', 'w')  # Create file with write(w) access
# hf.create_dataset('X_train', data=X_train)
# hf.create_dataset('y_train', data=y_train)
# hf.create_dataset('X_val', data=X_val)
# hf.create_dataset('y_val', data=y_val)
# hf.create_dataset('X_test', data=X_test)
# hf.close()

In [3]:
# Read normalized value from .h5 file
h5 = h5py.File('data_plant_seed_resizedImages_float_normalized.h5', 'r')
print(h5.keys())

X_train = h5['X_train'][:]
y_train = h5['y_train'][:]
X_val = h5['X_val'][:]
y_val = h5['y_val'][:]
# X_test = h5['X_test'][:]  # Don't read while modelling for saving memory

<KeysViewHDF5 ['X_test', 'X_train', 'X_val', 'y_train', 'y_val']>


In [4]:
batch_size = 128
num_classes = 12
epochs = 10
classLabel_inOrderOfIndex = ['Black-grass', 'Charlock', 'Cleavers', 'Common Chickweed', 
                             'Common wheat', 'Fat Hen', 'Loose Silky-bent', 'Maize', 
                             'Scentless Mayweed', 'Shepherds Purse', 'Small-flowered Cranesbill', 'Sugar beet']
input_shape = (res_dim_h, res_dim_w, 3)

In [5]:
from tensorflow import keras
from tensorflow.keras import models, backend
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Reshape, Dropout
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import categorical_crossentropy

In [6]:
# convert class vectors to binary class matrices
y_train_cat = keras.utils.to_categorical(y_train, num_classes)
y_val_cat = keras.utils.to_categorical(y_val, num_classes)

In [7]:
print(y_train_cat[0])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [9]:
# Buile CNN

#Initialize the model
model = Sequential()

#Add a Convolutional Layer with 32 filters of size 3X3 and activation function as 'ReLU' 
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape,name='conv_1'))

#Add a Convolutional Layer with 64 filters of size 3X3 and activation function as 'ReLU' 
model.add(Conv2D(64, (3, 3), activation='relu',name='conv_2'))

#Add a MaxPooling Layer of size 2X2 
model.add(MaxPooling2D(pool_size=(2, 2),name='max_1'))

#Apply Dropout with 0.25 probability 
model.add(Dropout(0.25,name='drop_1'))

#Flatten the layer
model.add(Flatten())

#Add Fully Connected Layer with 128 units and activation function as 'ReLU'
model.add(Dense(128, activation='relu',name='dense_1'))
#Apply Dropout with 0.5 probability 
model.add(Dropout(0.5,name='drop_2'))

#Add Fully Connected Layer with 10 units and activation function as 'softmax'
model.add(Dense(num_classes, activation='softmax',name='dense_2'))

In [10]:
#To use adam optimizer for learning weights with learning rate = 0.001
optimizer = Adam(lr=0.001)
#Set the loss function and optimizer for the model training
model.compile(loss=categorical_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train_cat,
          batch_size=batch_size,
          epochs=10,
          verbose=1,
          validation_data=(X_val, y_val_cat))

Train on 3325 samples, validate on 1425 samples
Epoch 1/10
3325/3325 [==============================] - 10s 3ms/sample - loss: 0.7461 - accuracy: 0.7149 - val_loss: 2.8983 - val_accuracy: 0.2716
Epoch 2/10
3325/3325 [==============================] - 10s 3ms/sample - loss: 0.7055 - accuracy: 0.7263 - val_loss: 2.9432 - val_accuracy: 0.2547
Epoch 3/10
3325/3325 [==============================] - 10s 3ms/sample - loss: 0.7012 - accuracy: 0.7341 - val_loss: 3.0683 - val_accuracy: 0.2611
Epoch 4/10
3325/3325 [==============================] - 10s 3ms/sample - loss: 0.6661 - accuracy: 0.7389 - val_loss: 3.0152 - val_accuracy: 0.2589
Epoch 5/10
3325/3325 [==============================] - 10s 3ms/sample - loss: 0.6147 - accuracy: 0.7642 - val_loss: 3.2727 - val_accuracy: 0.2618
Epoch 6/10
3325/3325 [==============================] - 10s 3ms/sample - loss: 0.6284 - accuracy: 0.7549 - val_loss: 3.4723 - val_accuracy: 0.2316
Epoch 7/10
3325/3325 [==============================] - 10s 3ms/sample

In [39]:
#Set the path where you want to store the model and weights. 

# model.save('./data/cnn_svhn.h5')
# model.save_weights('./data/cnn_svhn_weights.h5')

# STEP 4
Optimize the model (8 points)

In [22]:
# Build optimized CNN
    # Add BatchNormalization
    # Kernel_initialization = he_normal
    # More number of filters

#Initialize the model
model2 = Sequential()

#Add a Convolutional Layer with 32 filters of size 3X3 and activation function as 'ReLU' 
model2.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape,name='conv_1'))

#Add a Convolutional Layer with 64 filters of size 3X3 and activation function as 'ReLU' 
model2.add(Conv2D(64, (3, 3), activation='relu'))

#Add a MaxPooling Layer of size 2X2 
model2.add(MaxPooling2D(pool_size=(2, 2),name='max_1'))

#Add a Convolutional Layer with 64 filters of size 3X3 and activation function as 'ReLU' 
model2.add(Conv2D(32, (3, 3), activation='relu'))

#Add a MaxPooling Layer of size 2X2 
model2.add(MaxPooling2D(pool_size=(2, 2)))

#Add a Convolutional Layer with 64 filters of size 3X3 and activation function as 'ReLU' 
model2.add(Conv2D(16, (3, 3), activation='relu'))

#Apply Dropout with 0.25 probability 
model2.add(Dropout(0.25,name='drop_1'))

#Flatten the layer
model2.add(Flatten())

model2.add(keras.layers.BatchNormalization())
#Add Fully Connected Layer with 128 units and activation function as 'ReLU'
model2.add(Dense(64, activation='relu', kernel_initializer="he_normal"))
#Apply Dropout with 0.5 probability 
model2.add(Dropout(0.25,name='drop_2'))

# model2.add(keras.layers.BatchNormalization())
# #Add Fully Connected Layer with 128 units and activation function as 'ReLU'
# model2.add(Dense(32, activation='relu', kernel_initializer="he_normal"))
# #Apply Dropout with 0.5 probability 
# model2.add(Dropout(0.25))

#Add Fully Connected Layer with 10 units and activation function as 'softmax'
model2.add(Dense(num_classes, activation='softmax'))

In [23]:
#To use adam optimizer for learning weights with learning rate = 0.001
optimizer = Adam(lr=0.005)
#Set the loss function and optimizer for the model training
model2.compile(loss=categorical_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy'])

In [30]:
model2.fit(X_train, y_train_cat,
          batch_size=batch_size,
          epochs=10,
          verbose=1,
          validation_data=(X_val, y_val_cat))

Train on 3325 samples, validate on 1425 samples
Epoch 1/10
3325/3325 [==============================] - 10s 3ms/sample - loss: 0.3689 - accuracy: 0.8716 - val_loss: 4.4691 - val_accuracy: 0.2765
Epoch 2/10
3325/3325 [==============================] - 10s 3ms/sample - loss: 0.3794 - accuracy: 0.8743 - val_loss: 4.9982 - val_accuracy: 0.2877
Epoch 3/10
3325/3325 [==============================] - 9s 3ms/sample - loss: 0.3861 - accuracy: 0.8674 - val_loss: 4.8125 - val_accuracy: 0.2989
Epoch 4/10
3325/3325 [==============================] - 9s 3ms/sample - loss: 0.3232 - accuracy: 0.8950 - val_loss: 4.5556 - val_accuracy: 0.3067
Epoch 5/10
3325/3325 [==============================] - 9s 3ms/sample - loss: 0.3523 - accuracy: 0.8830 - val_loss: 4.4287 - val_accuracy: 0.2919
Epoch 6/10
3325/3325 [==============================] - 9s 3ms/sample - loss: 0.3967 - accuracy: 0.8656 - val_loss: 4.8462 - val_accuracy: 0.2835
Epoch 7/10
3325/3325 [==============================] - 9s 3ms/sample - lo

# STEP 5
Predict the accuracy for both train and validation data (7 points)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [32]:
y_train_pred_model2 = model2.predict(X_train)
y_val_pred_model2 = model2.predict(X_val)

In [34]:
# Use np.argmax to find the index of the max value in the row
confusion_matrix_train = confusion_matrix(np.argmax(y_train_cat, axis=1), np.argmax(y_train_pred_model2, axis=1))
confusion_matrix_val = confusion_matrix(np.argmax(y_val_cat, axis=1), np.argmax(y_val_pred_model2, axis=1))

print("Train data confusion matrix\n", confusion_matrix_train)
print("\n\nValidation data confusion matrix\n", confusion_matrix_val)

Train data confusion matrix
 [[174   0   0   0   0   0   2   0   0   0   1   1]
 [  0 280   0   0   0   0   0   0   0   0   1   0]
 [  0   0 210   0   0   0   0   0   0   0   0   0]
 [  0   0   0 424   0   0   0   0   0   0   0   0]
 [  0   0   1   0 166   0   1   0   0   0   0   0]
 [  0   0   0   0   0 334   0   0   0   0   0   0]
 [  0   0   0   2   0   0 455   0   0   0   0   0]
 [  0   0   0   0   0   1   0 154   0   0   0   0]
 [  0   0   0   3   0   0   0   0 361   0   0   0]
 [  0   0   0   1   0   0   0   0   0 156   0   0]
 [  0   0   0   0   0   0   0   0   0   0 340   0]
 [  0   0   0   0   0   0   1   0   0   0   0 256]]


Validation data confusion matrix
 [[17  2  0 14  5  6 30  0  2  1  3  5]
 [ 6 38  9  1  3  7  4  3  9  5 20  4]
 [ 1 15 25  8  3  5  2  0  4  6  7  1]
 [ 2  3  4 95  4  9 16  8 24  7  5 10]
 [ 3  2  2  8  9  4  7  2  5  1  1  9]
 [ 4  4  1 38  3 35 25  3  5  7 11  5]
 [14  4  1 43  2 13 73  0 10  5 14 18]
 [ 4  4  2 28  3  3  2 10  6  2  1  1]
 [ 4  3  0

In [41]:
accuracy_train = accuracy_score(np.argmax(y_train_cat, axis=1), np.argmax(y_train_pred_model2, axis=1))
accuracy_val = accuracy_score(np.argmax(y_val_cat, axis=1), np.argmax(y_val_pred_model2, axis=1))

print("Accuracy of training data on the model: ", accuracy_train)
print("Accuracy of validation data on the model: ", accuracy_val)

Accuracy of training data on the model:  0.9954887218045113
Accuracy of validation data on the model:  0.3045614035087719


# Inference
- The model has high bias
- As machine was not able to handle this large data, therefore, low resolution images(after resizing) were used. This probably caused lose of information which may have caused some accuracy lose.